### ISSUE TITLE
Open Source audit is required

### ISSUE THREAD

**Issue by hedss** [resin-io-modules/resin-config-writer#5]
So that we can OSS this ASAP.
Should follow the guidelines on the [HQ WIki](https://github.com/resin-io/hq/wiki/Open-Sourcing-Resin) and ensure there's nothing confidential, but I think this is probably a good component for getting out there.

**Comment by petrosagg** [comment]
@hedss should we close this? This repo is already public

**Comment by petrosagg** [comment]
Oops. I clicked "Close and commnet". Please re-open if needed

**Comment by lurch** [comment]
Yeah, from a quick look at the code this module relies on the external system commands `parted` and `mcopy` so I think it'd definitely be worth replacing usages of it with the 'pure' NodeJS modules that @zvin pointed out.
(and perhaps once that is done the README could be updated to indicate that this module is deprecated?)
